#!/usr/bin/env bash
# Ready Telegram MTProto proxy (mtg + Docker Compose)
set -euo pipefail

SCRIPT_DIR="$(CDPATH='' cd "$(dirname "$0")" && pwd)"
WORKDIR="${MTPROTO_WORKDIR:-$SCRIPT_DIR}"
ENV_FILE="$WORKDIR/.env"
COMPOSE_FILE="$WORKDIR/docker-compose.yml"
CONFIG_FILE="$WORKDIR/config.toml"
LINK_FILE="$WORKDIR/proxy-link.txt"

DEFAULT_PORT=443
DEFAULT_DOMAIN="cloudflare.com"

log()  { printf '==> %s\n' "$*"; }
ok()   { printf ' [OK] %s\n' "$*"; }
fail() { printf ' [FAIL] %s\n' "$*" >&2; exit 1; }

need_root_hint() {
  if [[ "${EUID}" -ne 0 ]] && ! command -v sudo >/dev/null 2>&1; then
    fail "Need root or sudo to install Docker / bind port 443"
  fi
}

run() {
  if [[ "${EUID}" -eq 0 ]]; then
    "$@"
  else
    sudo "$@"
  fi
}

compose() {
  if docker compose version >/dev/null 2>&1; then
    run docker compose -f "$COMPOSE_FILE" --project-directory "$WORKDIR" "$@"
  elif command -v docker-compose >/dev/null 2>&1; then
    run docker-compose -f "$COMPOSE_FILE" --project-directory "$WORKDIR" "$@"
  else
    fail "docker compose not found"
  fi
}

detect_ip() {
  local ip=""
  ip=$(curl -4 -fsS --connect-timeout 5 https://api.ipify.org 2>/dev/null \
    || curl -4 -fsS --connect-timeout 5 https://ifconfig.me 2>/dev/null \
    || curl -4 -fsS --connect-timeout 5 https://icanhazip.com 2>/dev/null \
    || true)
  ip=$(printf '%s' "$ip" | tr -d '[:space:]')
  if [[ -z "$ip" ]]; then
    fail "Could not detect public IP. Set VPS_IP in .env manually."
  fi
  printf '%s\n' "$ip"
}

# Fake-TLS secret: ee + 16 random bytes hex + domain as hex
hex_encode() {
  if command -v xxd >/dev/null 2>&1; then
    printf '%s' "$1" | xxd -p -c 256 | tr -d '\n'
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c 'import sys; print(sys.argv[1].encode().hex(), end="")' "$1"
  else
    # od fallback (POSIX-ish)
    printf '%s' "$1" | od -An -tx1 | tr -d ' \n'
  fi
}

generate_secret_openssl() {
  local domain="$1"
  local random domain_hex
  random=$(openssl rand -hex 16)
  domain_hex=$(hex_encode "$domain")
  [[ -n "$domain_hex" ]] || fail "Could not hex-encode domain (need xxd or python3)"
  printf 'ee%s%s\n' "$random" "$domain_hex"
}

generate_secret() {
  local domain="$1"
  local secret=""

  if command -v docker >/dev/null 2>&1; then
    secret=$(run docker run --rm nineseconds/mtg:2 generate-secret --hex "$domain" 2>/dev/null || true)
  fi

  if [[ -z "$secret" ]]; then
    secret=$(generate_secret_openssl "$domain")
  fi

  secret=$(printf '%s' "$secret" | tr -d '[:space:]')
  [[ "${secret:0:2}" == "ee" ]] || fail "Bad secret (expected ee… Fake-TLS): $secret"
  printf '%s\n' "$secret"
}

write_config() {
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  cat > "$CONFIG_FILE" <<EOF
# Generated by setup.sh — do not commit
secret = "${MTG_SECRET}"
bind-to = "0.0.0.0:${MTG_PORT}"
EOF
  ok "Wrote $CONFIG_FILE"
}

show_link() {
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  local link="tg://proxy?server=${VPS_IP}&port=${MTG_PORT}&secret=${MTG_SECRET}"
  local web="https://t.me/proxy?server=${VPS_IP}&port=${MTG_PORT}&secret=${MTG_SECRET}"

  cat <<EOF

========================================
  Telegram MTProto proxy is ready
========================================

Server : ${VPS_IP}
Port   : ${MTG_PORT}
Secret : ${MTG_SECRET}

Open in Telegram (preferred):
  ${link}

Or open in browser:
  ${web}

Manual: Settings → Data and Storage → Proxy → Add Proxy → MTProto
========================================
EOF

  printf '%s\n' "$link" > "$LINK_FILE"
  ok "Link saved to $LINK_FILE"
}

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    ok "Docker already installed: $(docker --version)"
    return
  fi
  need_root_hint
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | run sh
  if [[ "${EUID}" -ne 0 ]]; then
    run usermod -aG docker "$USER" || true
  fi
  ok "Docker installed"
}

open_firewall() {
  local port="$1"
  if command -v ufw >/dev/null 2>&1; then
    log "Opening firewall ports (ufw)..."
    run ufw allow OpenSSH >/dev/null 2>&1 || run ufw allow 22/tcp >/dev/null 2>&1 || true
    run ufw allow "${port}/tcp" >/dev/null 2>&1 || true
    run ufw --force enable >/dev/null 2>&1 || true
    ok "ufw: allowed ${port}/tcp"
  elif command -v firewall-cmd >/dev/null 2>&1; then
    run firewall-cmd --permanent --add-port="${port}/tcp" >/dev/null 2>&1 || true
    run firewall-cmd --reload >/dev/null 2>&1 || true
    ok "firewalld: allowed ${port}/tcp"
  else
    ok "No ufw/firewalld — ensure port ${port}/tcp is open in the VPS panel"
  fi
}

cmd_link() {
  [[ -f "$ENV_FILE" ]] || fail "No .env — run ./setup.sh first"
  show_link
}

cmd_status() {
  [[ -f "$ENV_FILE" ]] || fail "No .env — run ./setup.sh first"
  compose ps
}

cmd_stop() {
  [[ -f "$COMPOSE_FILE" ]] || fail "docker-compose.yml missing"
  compose down
  ok "Proxy stopped"
}

cmd_install() {
  need_root_hint
  [[ -f "$COMPOSE_FILE" ]] || fail "docker-compose.yml not found next to setup.sh"

  local port="${MTG_PORT:-$DEFAULT_PORT}"
  local domain="${MTG_DOMAIN:-$DEFAULT_DOMAIN}"

  install_docker
  open_firewall "$port"

  mkdir -p "$WORKDIR"

  if [[ -f "$ENV_FILE" ]] && grep -q '^MTG_SECRET=ee' "$ENV_FILE"; then
    log "Existing .env found — keeping secret, refreshing config & containers"
  else
    log "Detecting public IP..."
    local ip
    ip="${VPS_IP:-$(detect_ip)}"
    ok "VPS IP: $ip"

    log "Generating Fake-TLS secret (domain: $domain)..."
    local secret
    secret=$(generate_secret "$domain")
    ok "Secret generated"

    cat > "$ENV_FILE" <<EOF
VPS_IP=${ip}
MTG_PORT=${port}
MTG_DOMAIN=${domain}
MTG_SECRET=${secret}
EOF
    ok "Wrote $ENV_FILE"
  fi

  write_config

  log "Pulling images and starting proxy..."
  compose pull
  compose up -d

  sleep 2
  if compose ps | grep -Eqi 'Up|running'; then
    ok "Container is running"
  else
    fail "Container not running — check: docker compose -f $COMPOSE_FILE ps"
  fi

  show_link
  echo "Later: ./setup.sh link | status | stop | reinstall"
}

cmd_reinstall() {
  [[ -f "$ENV_FILE" ]] && rm -f "$ENV_FILE" "$CONFIG_FILE" "$LINK_FILE"
  unset VPS_IP MTG_SECRET
  cmd_install
}

usage() {
  cat <<EOF
Usage: ./setup.sh [command]

  (default)   Install Docker (if needed), generate secret, start MTProto proxy
  link        Print tg:// connection link
  status      Show container status
  stop        Stop proxy
  reinstall   Generate a new secret and redeploy

Env overrides:
  MTG_PORT=443 MTG_DOMAIN=cloudflare.com VPS_IP=1.2.3.4 ./setup.sh
EOF
}

main() {
  case "${1:-install}" in
    install|"") cmd_install ;;
    link)       cmd_link ;;
    status)     cmd_status ;;
    stop)       cmd_stop ;;
    reinstall)  cmd_reinstall ;;
    -h|--help|help) usage ;;
    *) fail "Unknown command: $1 (see --help)" ;;
  esac
}

main "$@"
